name: beta

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: windows-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Download and Install Playit
      run: |
        Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe" -OutFile "$env:USERPROFILE\playit.exe"
        Start-Sleep -Seconds 5  # Give some time for the download to complete

    # Default, optional.
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "${{ secrets.MASTER_PASSWORD }}" -Force)
    
    # Run wallpaper.bat file (assuming it's located in the root directory of your repository)
    - name: Run wallpaper.bat
      run: |
        Start-Process -FilePath "$env:GITHUB_WORKSPACE\wallpaper.bat" -NoNewWindow -Wait
        
    # Run startup.bat file (assuming it's located in the root directory of your repository)
    - name: Run startup.bat
      run: |
        Start-Process -FilePath "$env:GITHUB_WORKSPACE\startup.bat" -NoNewWindow -Wait
        
    # Add custom user with full name as username
    - name: Add custom user
      run: |
        $username = "Admin"
        $password = ConvertTo-SecureString "${{ secrets.MASTER_PASSWORD }}" -AsPlainText -Force
        New-LocalUser -Name $username -Password $password -FullName $username -Description "Custom user for RDP access"
        Add-LocalGroupMember -Group "Administrators" -Member $username  # Optionally add user to Administrators group

    - name: Start Playit and Set Up RDP Tunnel
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }}
        PLAYIT_CUSTOM_DOMAIN: "rdp.megablue.nyc.mn"  # Add your custom domain here
      run: |
        # Ensure the Playit service starts with the custom domain
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -ArgumentList "--secret $env:PLAYIT_AUTH_KEY --domain $env:PLAYIT_CUSTOM_DOMAIN" -NoNewWindow -Wait
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -NoNewWindow

    # Prevent workflow from stopping
    - name: Keep the GitHub Action Runner Alive
      run: |
          Start-Sleep -Seconds 11800  # Adjust the duration based on your needs
